### ISSUE TITLE
Connection - FTP, SSH;

### ISSUE THREAD

**Issue by MHWcreations** [CM2Walki/Squad#15]
Hello,

ist there any option to connect via SSH or FTP to the container?

Or is there an option to install any apps (FTP-server, SSH-server, ...) in the container?

Best Regards MHW

**Comment by CM2Walki** [comment]
There are no preinstalled ways of accessing the container from the outside, since this is a bare-minimum setup of a Squad server. Here are some ways of how you can achieve the desired behavior though:

If only you need to access the server files you can use `docker exec -it [name] bash` (and then use nano, comes preinstalled with this image). If you need to copy files into the container, you can install _wget_ or _curl_ inside the container or use `docker cp [...]`.

If you need to provide access to another person without giving them access to the host (I use this approach):
Use a [bind mount](https://docs.docker.com/storage/bind-mounts/) on the host to store the container's game server files, then setup a [chroot sftp](https://www.thegeekstuff.com/2012/03/chroot-sftp-setup/) for the directory. WinSCP and Filezilla both support sftp.

Note: Even though it's possible to install a ftp and/or ssh server inside the container, I wouldn't recommend it, as it will make the container non-interchangeable. Using a bind mount and the host's ssh server (as described above) allows you to redeploy the container without data & configuration loss.
